apiVersion: 1

datasources:
  - name: TestInfra MariaDB
    uid: testinfra-mariadb
    type: mysql
    access: proxy
    url: localhost:3306
    user: testinfra_user
    jsonData:
      database: testinfra_reports
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      tlsAuth: false
    secureJsonData:
      password: ''
    isDefault: false
    editable: true
