[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pytest-testinfra-exporter"
version = "0.3.0"
description = "Pytest plugin that reports testinfra results to MariaDB or PostgreSQL backends and visualizes on Grafana."
maintainers = [
    { name = "Udeshya Giri", email = "udeshyagiri@gmail.com" },
    { name = "Udeshya Giri", email = "udeshya.giri@phonepe.com" },
    { name = "Aniruddha Thombre", email = "aniruddha@aniruddhas.com" },
    { name = "Aniruddha Thombre", email = "aniruddha.t@phonepe.com" }
]
license = "Apache-2.0"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9"
dependencies = [
    "pytest>=7.0",
    "PyYAML>=6.0",
]
keywords = ["pytest", "plugin", "testinfra", "mariadb", "postgres", "pytest-testinfra", "grafana"]
classifiers = [
    "Framework :: Pytest",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.entry-points.pytest11]
pytest_testinfra_exporter = "pytest_testinfra_exporter"

[project.optional-dependencies]
mariadb = ["PyMySQL>=1.1"]
postgres = ["psycopg2-binary>=2.9"]

[tool.setuptools]
include-package-data = true
packages = [
    "pytest_testinfra_exporter",
    "pytest_testinfra_exporter.backends",
]

[tool.setuptools.package-dir]
pytest_testinfra_exporter = "."
"pytest_testinfra_exporter.backends" = "backends"

[tool.setuptools.package-data]
pytest_testinfra_exporter = [
    "failure_mapper/*.yaml",
    "datastores/*.yaml",
    "schema/*.sql",
]