apiVersion: 1

datasources:
  - name: TestInfra Postgres
    uid: testinfra-postgres
    type: postgres
    access: proxy
    url: localhost:5432
    user: postgres
    jsonData:
      database: testinfra_reports
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    secureJsonData:
      password: ''
    isDefault: false
    editable: true
